Determining if the pthread_create exist failed with the following output:
Change Dir: /home/pyp/face_app/face_platform/models/data_source/cmake-build-debug/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_ddf86/fast"
make[1]: Entering directory '/home/pyp/face_app/face_platform/models/data_source/cmake-build-debug/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_ddf86.dir/build.make CMakeFiles/cmTC_ddf86.dir/build
make[2]: Entering directory '/home/pyp/face_app/face_platform/models/data_source/cmake-build-debug/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ddf86.dir/CheckSymbolExists.c.o
/usr/bin/cc   -fPIC    -o CMakeFiles/cmTC_ddf86.dir/CheckSymbolExists.c.o   -c /home/pyp/face_app/face_platform/models/data_source/cmake-build-debug/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_ddf86
/home/pyp/clion-2018.1.2/bin/cmake/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ddf86.dir/link.txt --verbose=1
/usr/bin/cc -fPIC     CMakeFiles/cmTC_ddf86.dir/CheckSymbolExists.c.o  -o cmTC_ddf86 
CMakeFiles/cmTC_ddf86.dir/CheckSymbolExists.c.o：在函数‘main’中：
CheckSymbolExists.c:(.text+0x1b)：对‘pthread_create’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_ddf86.dir/build.make:97: recipe for target 'cmTC_ddf86' failed
make[2]: *** [cmTC_ddf86] Error 1
make[2]: Leaving directory '/home/pyp/face_app/face_platform/models/data_source/cmake-build-debug/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_ddf86/fast' failed
make[1]: *** [cmTC_ddf86/fast] Error 2
make[1]: Leaving directory '/home/pyp/face_app/face_platform/models/data_source/cmake-build-debug/CMakeFiles/CMakeTmp'

File /home/pyp/face_app/face_platform/models/data_source/cmake-build-debug/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/pyp/face_app/face_platform/models/data_source/cmake-build-debug/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_ea7c8/fast"
make[1]: Entering directory '/home/pyp/face_app/face_platform/models/data_source/cmake-build-debug/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_ea7c8.dir/build.make CMakeFiles/cmTC_ea7c8.dir/build
make[2]: Entering directory '/home/pyp/face_app/face_platform/models/data_source/cmake-build-debug/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ea7c8.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_ea7c8.dir/CheckFunctionExists.c.o   -c /home/pyp/clion-2018.1.2/bin/cmake/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_ea7c8
/home/pyp/clion-2018.1.2/bin/cmake/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ea7c8.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_ea7c8.dir/CheckFunctionExists.c.o  -o cmTC_ea7c8 -lpthreads 
/usr/bin/ld: 找不到 -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_ea7c8.dir/build.make:97: recipe for target 'cmTC_ea7c8' failed
make[2]: *** [cmTC_ea7c8] Error 1
make[2]: Leaving directory '/home/pyp/face_app/face_platform/models/data_source/cmake-build-debug/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_ea7c8/fast' failed
make[1]: *** [cmTC_ea7c8/fast] Error 2
make[1]: Leaving directory '/home/pyp/face_app/face_platform/models/data_source/cmake-build-debug/CMakeFiles/CMakeTmp'


