Determining if the pthread_create exist failed with the following output:
Change Dir: /home/pyp/face_app/face_platform/models/recognization/cmake-build-debug/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_c8bcc/fast"
make[1]: Entering directory '/home/pyp/face_app/face_platform/models/recognization/cmake-build-debug/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_c8bcc.dir/build.make CMakeFiles/cmTC_c8bcc.dir/build
make[2]: Entering directory '/home/pyp/face_app/face_platform/models/recognization/cmake-build-debug/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c8bcc.dir/CheckSymbolExists.c.o
/usr/bin/cc   -fPIC    -o CMakeFiles/cmTC_c8bcc.dir/CheckSymbolExists.c.o   -c /home/pyp/face_app/face_platform/models/recognization/cmake-build-debug/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_c8bcc
/home/pyp/clion-2018.1.2/bin/cmake/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c8bcc.dir/link.txt --verbose=1
/usr/bin/cc -fPIC     CMakeFiles/cmTC_c8bcc.dir/CheckSymbolExists.c.o  -o cmTC_c8bcc 
CMakeFiles/cmTC_c8bcc.dir/CheckSymbolExists.c.o：在函数‘main’中：
CheckSymbolExists.c:(.text+0x1b)：对‘pthread_create’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_c8bcc.dir/build.make:97: recipe for target 'cmTC_c8bcc' failed
make[2]: *** [cmTC_c8bcc] Error 1
make[2]: Leaving directory '/home/pyp/face_app/face_platform/models/recognization/cmake-build-debug/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_c8bcc/fast' failed
make[1]: *** [cmTC_c8bcc/fast] Error 2
make[1]: Leaving directory '/home/pyp/face_app/face_platform/models/recognization/cmake-build-debug/CMakeFiles/CMakeTmp'

File /home/pyp/face_app/face_platform/models/recognization/cmake-build-debug/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/pyp/face_app/face_platform/models/recognization/cmake-build-debug/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_6f6f0/fast"
make[1]: Entering directory '/home/pyp/face_app/face_platform/models/recognization/cmake-build-debug/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_6f6f0.dir/build.make CMakeFiles/cmTC_6f6f0.dir/build
make[2]: Entering directory '/home/pyp/face_app/face_platform/models/recognization/cmake-build-debug/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_6f6f0.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_6f6f0.dir/CheckFunctionExists.c.o   -c /home/pyp/clion-2018.1.2/bin/cmake/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_6f6f0
/home/pyp/clion-2018.1.2/bin/cmake/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6f6f0.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_6f6f0.dir/CheckFunctionExists.c.o  -o cmTC_6f6f0 -lpthreads 
/usr/bin/ld: 找不到 -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_6f6f0.dir/build.make:97: recipe for target 'cmTC_6f6f0' failed
make[2]: *** [cmTC_6f6f0] Error 1
make[2]: Leaving directory '/home/pyp/face_app/face_platform/models/recognization/cmake-build-debug/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_6f6f0/fast' failed
make[1]: *** [cmTC_6f6f0/fast] Error 2
make[1]: Leaving directory '/home/pyp/face_app/face_platform/models/recognization/cmake-build-debug/CMakeFiles/CMakeTmp'


